version: "3.9"

services:
  
  django:
    build: .
    command: sh -c 'python3 manage.py makemigrations; python3 manage.py migrate; python3 manage.py runserver 0.0.0.0:80'
    container_name: studysignsproject-django
    ports:
      - "80:80"
    depends_on:
      - postgres
    env_file:
      - ./.env
    links:
      - postgres:postgres
    networks:
      - djangonetwork

  postgres:
    image: postgres:latest
    container_name: studysignsproject-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_NAME_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    networks:
      - djangonetwork

  pgadmin:
    image: dpage/pgadmin4:6.12
    container_name: studysignsproject-pgadmin
    ports:
      - "5434:5434"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - djangonetwork

networks:
  djangonetwork:
    driver: bridge

volumes:
  postgres_volume:
  pgadmin: