version: '3.9'
services:
  nginx:
    container_name: core_web
    restart: on-failure
    image: nginx:stable
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    ports:
      - "80:80"
    depends_on:
      - api
  api:
    container_name: core_app
    build: .
    restart: always
    expose:
      - "5000"
    command: >
      sh -c " chmod 777 .env &&
              sed -i 's/^DEBUG=.*/DEBUG=False/' .env &&
              sed -i 's/^ALLOWED_HOSTS=.*/ALLOWED_HOSTS=localhost/' .env &&
              python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py collectstatic --noinput &&
          gunicorn Проект_по_созданию_обучающего_сайта_топографических_знаков.wsgi:application --bind 0.0.0.0:5000"
    volumes:
     - static_volume:/app/staticfiles

volumes:
  static_volume:
